# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

############################################
# LOCAL ENVIRONMENTS
############################################
development:
  <<: *default
  database: exercice_lewagon_rails_watch_list_development
  host: localhost
  username: thomas # <<< TRÈS IMPORTANT : ASSURE-TOI QUE C'EST BIEN 'thomas'
  # password:       # <<< LAISSE CETTE LIGNE COMMENTÉE

test:
  <<: *default
  database: exercice_lewagon_rails_watch_list_test
  host: localhost
  username: thomas # <<< TRÈS IMPORTANT : ASSURE-TOI QUE C'EST BIEN 'thomas'
  # password:       # <<< LAISSE CETTE LIGNE COMMENTÉE

############################################
# PRODUCTION  (Heroku)
############################################
production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

# config/storage.yml
cloudinary:
  service: Cloudinary
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
