# PostgreSQL. Versions 9.3 and up are supported.
#
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

############################################
# LOCAL ENVIRONMENTS
############################################
development:
  <<: *default
  database: exercice_lewagon_rails_watch_list_development
  host: localhost
  # username: postgres
  # password:

test:
  <<: *default
  database: exercice_lewagon_rails_watch_list_test
  host: localhost
  # username: postgres
  # password:

############################################
# PRODUCTION  (Heroku)
############################################
production:
  # Base principale de l’application
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  # Base utilisée par Rails 8 pour solid_cache
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
